# Generated by Django 5.1.4 on 2024-12-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=255, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('option_4', models.CharField(max_length=255)),
                ('answer', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
    ]
