# Generated by Django 5.1.4 on 2024-12-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option_1',
            new_name='choice_1',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_2',
            new_name='choice_2',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_3',
            new_name='choice_3',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='option_4',
            new_name='choice_4',
        ),
    ]
